sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t neerajrajasekar/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true neerajrajasekar/docker-react npm run test